# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XV2L8kyyaBC0Kmyvha0wN4C-SLEm_aII
"""

# pip install streamlit

import streamlit as st
import pandas as pd
import joblib
model=joblib.load('Mall_Customer_prediction.pkl')
scaler=joblib.load('standard_scaler.pkl')

if(st.button("Predict Cluster (classify)")):
  input_data=pd.DataFrame([[income,score]],columnd=['Annual Income (k$)', 'Spending Score (1-100)'])
  scaled=scaler.transform(input_data)
  cluster=model.predict(scaled)
  st.success(f"This customer belomgs to cluster ")



if(st.button("Predict Cluster (classify)")):
  input_data=pd.DataFrame([[income,score]],columnd=['Annual Income (k$)', 'Spending Score (1-100)'])
  scaled=scaler.transform(input_data)
  cluster=model.predict(scaled)
  st.success(f"This customer belomgs to cluster ")